apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-helloworld
  name: python-helloworld
  namespace: default 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: python-helloworld
    spec:
      containers:
      - image: william861227/python-hello-world:latest 
        imagePullPolicy: IfNotPresent
        name: python-helloworld
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
